## roles/ansible-role-ipa-client/tasks/main.yml
# vim:ft=yaml.ansible:
---
- name: Include distribution specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'

- name: Install required packages
  package:
    name: '{{ ipa_client_pkgs }}'
    state: present

- name: Add host to IPA server
  ipa_host:
    name: '{{ ansible_fqdn }}'
    description: '{{ ipa_description }}'
    force: '{{ ipaclient_force_join }}'
    ip_address: '{{ ansible_default_ipv4.address }}'
    ipa_host: '{{ ipaserver }}'
    ipa_pass: '{{ ipaadmin_password }}'
    ipa_user: '{{ ipaadmin_principal }}'
    ipa_prot: https
    mac_address: '{{ ansible_default_ipv4.macaddress }}'
    ns_hardware_platform: '{{ ipa_ns_hw }}'
    ns_host_location: '{{ ipa_ns_loc }}'
    ns_os_version: '{{ ansible_distribution }} {{ ansible_distribution_version }}'
    state: '{{ ipaclient_state }}'
    update_dns: '{{ ipaclient_update_dns }}'
    validate_certs: '{{ ipa_validate_certs }}'
  ignore_errors: yes

- name: Add CNAMEs for host
  when: ipaclient_cnames is defined
  ipa_dnsrecord:
    record_type: CNAME
    record_name: '{{ item }}'
    record_value: '{{ ansible_nodename }}'
    zone_name: '{{ ipaserver_domain }}'
    ipa_host: '{{ ipaserver }}'
    ipa_pass: '{{ ipaadmin_password }}'
    ipa_user: '{{ ipaadmin_principal }}'
    ipa_prot: https
    state: '{{ ipaclient_state }}'
    validate_certs: '{{ ipa_validate_certs }}'
  with_items: '{{ ipaclient_cnames }}'

- name: Enroll host in domain
  args:
    creates: /etc/ipa/default.conf
  command: >
    {{ ipaclient_install_command }}
    {{ '--hostname=' + ansible_fqdn }}
    --server={{ ipaserver }}
    --domain={{ ipaserver_domain }}
    --principal={{ ipaadmin_principal }}
    --password={{ ipaadmin_password }}
    --ssh-trust-dns
    {{ '--mkhomedir' if ipaclient_mkhomedir else '' }}
    --unattended
    {{ '--no-ntp' if ipaclient_no_ntp else '' }}
    {{ '--force-join' if ipaclient_force_join else '' }}

- name: Enable mkhomedir (Ubuntu)
  when: "'Ubuntu' in ansible_distribution"
  lineinfile:
    dest: /etc/pam.d/common-session
    line: 'session     required      pam_mkhomedir.so skel=/etc/skel umask=0022'

- name: Enable sssd sudo functionality (Ubuntu)
  when: "'Ubuntu' in ansible_distribution"
  notify:
    - restart sssd
    - restart ssh
  lineinfile:
    dest: /etc/sssd/sssd.conf
    regexp: '^services.*'
    line: 'services = nss, pam, ssh, sudo'
...
